version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'deps'
      prefix-development: 'deps-dev'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'npm'
    assignees:
      - 'pdugan20'
    reviewers:
      - 'pdugan20'
    groups:
      dev-dependencies:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
      production-dependencies:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'ci'
    labels:
      - 'dependencies'
      - 'github-actions'
    assignees:
      - 'pdugan20'
    reviewers:
      - 'pdugan20'
    groups:
      github-actions:
        patterns: ['*']
        update-types:
          - 'minor'
          - 'patch'
